window.opacity = 1.0

[general]
live_config_reload = true
import = ["./themes/wallbash.toml"]

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[env]
TERM = "xterm-256color"

[terminal]

[terminal.shell]
program = "/usr/bin/fish"

[window.padding]
x = 20
y = 20
