- name: nvim
  source: /home/sumit/dotfiles/dots/nvim
  status: Linked
  target: /home/sumit/.config/nvim
- name: mpv
  source: /home/sumit/dotfiles/dots/mpv
  status: Linked
  target: /home/sumit/.config/mpv
- name: btop
  source: /home/sumit/dotfiles/dots/btop
  status: Linked
  target: /home/sumit/.config/btop
- name: fish
  source: /home/sumit/dotfiles/dots/fish
  status: Linked
  target: /home/sumit/.config/fish
- name: ghostty
  source: /home/sumit/dotfiles/dots/ghostty
  status: Linked
  target: /home/sumit/.config/ghostty
- name: fastfetch
  source: /home/sumit/dotfiles/dots/fastfetch
  status: Linked
  target: /home/sumit/.config/fastfetch
- name: alacritty
  source: /home/sumit/dotfiles/dots/alacritty
  status: Linked
  target: /home/sumit/.config/alacritty
- name: hyprpanel
  source: /home/sumit/dotfiles/dots/hyprpanel
  status: Linked
  target: /home/sumit/.config/hyprpanel
- name: ohmyposh
  source: /home/sumit/dotfiles/dots/ohmyposh
  status: Linked
  target: /home/sumit/.config/ohmyposh
- name: yazi
  source: /home/sumit/dotfiles/dots/yazi
  status: Linked
  target: /home/sumit/.config/yazi
- name: zed
  source: /home/sumit/dotfiles/dots/zed
  status: Linked
  target: /home/sumit/.config/zed
- name: nushell
  source: /home/sumit/dotfiles/dots/nushell
  status: Linked
  target: /home/sumit/.config/nushell
- name: HyprUserPref
  source: /home/sumit/dotfiles/dots/userprefs.conf
  status: Linked
  target: /home/sumit/.config/hypr/userprefs.conf
- name: HydeWallbash
  source: /home/sumit/dotfiles/dots/hydewallbash/*
  status: Linked
  target: /home/sumit/.config/hyde/wallbash/always
