[colors.primary]
foreground = "#FFFFFF"
background = "#1C0725"
dim_foreground = "#1C0725"
bright_foreground = "#FFFFFF"

[colors.cursor]
text = "#070707"
cursor = "#ECE8BB"

[colors.vi_mode_cursor]
text = "#070707"
cursor = "#ECE8BB"

[colors.search.matches]
foreground = "#FFFFFF"
background = "#1C0725"

[colors.search.focused_match]
foreground = "#1C0725"
background = "#FFFFFF"

[colors.hints.start]
foreground = "#FFFFFF"
background = "#1C0725"

[colors.hints.end]
foreground = "#FFFFFF"
background = "#1C0725"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#FFFFFF"
background = "#1C0725"

[colors.selection]
text = "#FFFFFF"
background = "#1C0725"

[colors.normal]
black = "#7E578F"
red = "#FFFBCC"
green = "#FFCCF7"
yellow = "#F5CCFF"
blue = "#E69ADA"
magenta = "#E69ADA"
cyan = "#D79AE6"
white = "#E6DF9A"

[colors.bright]
black = "#7E578F"
red = "#FFFBCC"
green = "#FFCCF7"
yellow = "#F5CCFF"
blue = "#E69ADA"
magenta = "#E69ADA"
cyan = "#D79AE6"
white = "#E6DF9A"

[colors.dim]
black = "#7E578F"
red = "#FFFBCC"
green = "#FFCCF7"
yellow = "#F5CCFF"
blue = "#E69ADA"
magenta = "#E69ADA"
cyan = "#D79AE6"
white = "#E6DF9A"

