[colors.primary]
foreground = "#FFFFFF"
background = "#1D272C"
dim_foreground = "#1D272C"
bright_foreground = "#FFFFFF"

[colors.cursor]
text = "#080808"
cursor = "#BCCCDC"

[colors.vi_mode_cursor]
text = "#080808"
cursor = "#BCCCDC"

[colors.search.matches]
foreground = "#FFFFFF"
background = "#1D272C"

[colors.search.focused_match]
foreground = "#1D272C"
background = "#FFFFFF"

[colors.hints.start]
foreground = "#FFFFFF"
background = "#1D272C"

[colors.hints.end]
foreground = "#FFFFFF"
background = "#1D272C"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#FFFFFF"
background = "#1D272C"

[colors.selection]
text = "#FFFFFF"
background = "#1D272C"

[colors.normal]
black = "#577C8F"
red = "#CCE6FF"
green = "#CCE1FF"
yellow = "#FFD6CC"
blue = "#9AB9E6"
magenta = "#9AB9E6"
cyan = "#E6A99A"
white = "#9AC0E6"

[colors.bright]
black = "#577C8F"
red = "#CCE6FF"
green = "#CCE1FF"
yellow = "#FFD6CC"
blue = "#9AB9E6"
magenta = "#9AB9E6"
cyan = "#E6A99A"
white = "#9AC0E6"

[colors.dim]
black = "#577C8F"
red = "#CCE6FF"
green = "#CCE1FF"
yellow = "#FFD6CC"
blue = "#9AB9E6"
magenta = "#9AB9E6"
cyan = "#E6A99A"
white = "#9AC0E6"

