[colors.primary]
foreground = "#080808"
background = "#BCC1DB"
dim_foreground = "#BCC1DB"
bright_foreground = "#080808"

[colors.cursor]
text = "#FFFFFF"
cursor = "#565F85"

[colors.vi_mode_cursor]
text = "#FFFFFF"
cursor = "#565F85"

[colors.search.matches]
foreground = "#080808"
background = "#BCC1DB"

[colors.search.focused_match]
foreground = "#BCC1DB"
background = "#080808"

[colors.hints.start]
foreground = "#080808"
background = "#BCC1DB"

[colors.hints.end]
foreground = "#080808"
background = "#BCC1DB"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#080808"
background = "#BCC1DB"

[colors.selection]
text = "#080808"
background = "#BCC1DB"

[colors.normal]
black = "#7A86C2"
red = "#293152"
green = "#522935"
yellow = "#292D52"
blue = "#7D4B5A"
magenta = "#7D4B5A"
cyan = "#4B507D"
white = "#4B557D"

[colors.bright]
black = "#7A86C2"
red = "#293152"
green = "#522935"
yellow = "#292D52"
blue = "#7D4B5A"
magenta = "#7D4B5A"
cyan = "#4B507D"
white = "#4B557D"

[colors.dim]
black = "#7A86C2"
red = "#293152"
green = "#522935"
yellow = "#292D52"
blue = "#7D4B5A"
magenta = "#7D4B5A"
cyan = "#4B507D"
white = "#4B557D"

