[colors.primary]
foreground = "#FFFFFF"
background = "#363949"
dim_foreground = "#363949"
bright_foreground = "#FFFFFF"

[colors.cursor]
text = "#111110"
cursor = "#878BA6"

[colors.vi_mode_cursor]
text = "#111110"
cursor = "#878BA6"

[colors.search.matches]
foreground = "#FFFFFF"
background = "#363949"

[colors.search.focused_match]
foreground = "#363949"
background = "#FFFFFF"

[colors.hints.start]
foreground = "#FFFFFF"
background = "#363949"

[colors.hints.end]
foreground = "#FFFFFF"
background = "#363949"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#FFFFFF"
background = "#363949"

[colors.selection]
text = "#FFFFFF"
background = "#363949"

[colors.normal]
black = "#57608F"
red = "#CCD3FF"
green = "#CCD3FF"
yellow = "#CCD3FF"
blue = "#9AA4E6"
magenta = "#9AA4E6"
cyan = "#9AA4E6"
white = "#9AA4E6"

[colors.bright]
black = "#57608F"
red = "#CCD3FF"
green = "#CCD3FF"
yellow = "#CCD3FF"
blue = "#9AA4E6"
magenta = "#9AA4E6"
cyan = "#9AA4E6"
white = "#9AA4E6"

[colors.dim]
black = "#57608F"
red = "#CCD3FF"
green = "#CCD3FF"
yellow = "#CCD3FF"
blue = "#9AA4E6"
magenta = "#9AA4E6"
cyan = "#9AA4E6"
white = "#9AA4E6"

